config/routes.rb
Rails.application.routes.draw do
	root to: 'books#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 get '/books' => 'books#index'
 post '/books' => 'books#create'
 get '/books/:id/edit' => 'books#edit', as: 'edit_book'
 get '/books/:id' => 'books#show', as: 'book'
 patch '/books/:id' => 'books#update', as: 'update_books'
 put '/books/:id' => 'books#update'
 delete '/books/:id' => 'books#destroy', as: 'destroy_books'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
  	@book = Book.new
  	@books = Book.all
  end

  def show
  	@book = Book.find(params[:id])
  end

  def create
	@book = Book.new(book_params)
  	if @book.save
  		flash[:notice] = "Book was successfully created."
  		redirect_to book_path(@book.id)
    else
    	@books = Book.all
    	render :index
    end
  end

  def edit
  	@book = Book.find(params[:id])
  end
  def  update
	@book = Book.find(params[:id])
	if @book.update(book_params)
		flash[:notice] = "Book was successfully updated."
		redirect_to book_path(@book.id)
	else
      render :edit
    end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path
  end

  private
  def book_params
	params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
	
<% end %>
<h2>Editing Book</h2>
<% if @book.errors.any? %>
	<%= @book.errors.count %>errors prohibited this book from being saved:<br>
	<% @book.errors.full_messages.each do |msg| %>
	<%= msg %>
	<% end %>
<% end %>
	<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>

		<h4>title</h4>
		<%= f.text_field :title %>
		
		<h4>body</h4>
		<%= f.text_area :body %>
		<br><%= f.submit 'Update Book' %>
	
	<% end %>
	<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>


		<thead>
		<tr>
			<th>Title</th>
			<th>Body</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<% @books.each do |book| %>
	<tbody>
		<tr>
			<td><%= book.title %></td>
			<td><%= book.body %></td>
			<td><%= link_to "Show", book_path(book.id) %></td>
			<td><%= link_to "Edit", edit_book_path(book.id) %></td>
			<td><%= link_to "Destroy", destroy_books_path(book.id), method: :delete, "data-confirm" =>"Are you sure?" %></td>
		</tr>
	</tbody>
	<% end %>
</table>

<h2>New book</h2>
<% if @book.errors.any? %>
	<%= @book.errors.count %>errors prohibited this book from being saved:<br>
	<% @book.errors.full_messages.each do |msg| %>
	<%= msg %>
	<% end %>
<% end %>
	<%= form_for(@book) do |f| %>
		
		<h4>title</h4>
		<%= f.text_field :title %>
		
		<h4>body</h4>
		<%= f.text_area :body %>
		<br><%= f.submit 'Create Book' %>
	
	<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>

<h3>title:</h3>
<p><%= @book.title %></p>
<h3>Body:</h3>
<p><%= @book.body %></p>
<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/books/top.html.erb
<h4>ようこそ Bookers へ！</h4>

<div main>
	<span>Bookers</span>さまざまな書籍に関するあなたの意見や
	<br>印象を共有し交換することができます
    <br><%= link_to "start", books_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>